# CircleCI Config
version: 2

defaults_run: &defaults_run
  name: run defaults
  command: |
    echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    git config user.name "$GIT_NAME"
    git config user.email "$GIT_EMAIL"

jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          <<: *defaults_run
      - run: |
          npm i
          npm run build
          npm test
      - save_cache:
          key: dialog-components-{{ .Branch }}
          paths:
            - node_modules

  deployment:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dialog-components-{{ .Branch }}
      - run:
          <<: *defaults_run
      - run: |
          npm run docs

  npm_publish_prerelease:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          <<: *defaults_run
      - run: |
          if [ -z "$CIRCLE_PR_USERNAME" ]
          then
            npm version prerelease --preid=${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM} --ignore-scripts
            npm publish --tag=${CIRCLE_BRANCH}
          fi

  npm_publish_release:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          <<: *defaults_run
      - run: |
          npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - npm_publish_release:
          requires:
            - build
          filters:
            branches:
              only: master
      - npm_publish_prerelease:
          requires:
            - build
          filters:
            branches:
              ignore: master
